context:
  version: "2.46.0"

package:
  name: dex
  version: ${{ version }}

source:
  url: https://github.com/dexidp/dex/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 3c09c0f2be88719d5bc2a061d3df9310052c8220b651a3b72d774eecd9b50b65
  target_directory: src

build:
  number: 0
  script:
    - cd src/cmd/dex
    - go-licenses save . --save_path ../../../library_licenses --ignore github.com/dexidp/dex
    - if: unix
      then:
        - go build -v -o $PREFIX/bin/dex -ldflags="-s -w -X main.version=${{ version }}" .
        - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
        - $PREFIX/bin/dex completion zsh > $PREFIX/share/zsh/site-functions/_dex
        - $PREFIX/bin/dex completion bash > $PREFIX/share/bash-completion/completions/dex
        - $PREFIX/bin/dex completion fish > $PREFIX/share/fish/vendor_completions.d/dex.fish
      else: go build -v -o %LIBRARY_BIN%\dex.exe -ldflags="-s -X main.version=${{ version }}" .
requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: dex -h
  - package_contents:
      bin:
        - dex
      files:
        - if: unix
          then:
            - share/bash-completion/completions/dex
            - share/fish/vendor_completions.d/dex.fish
            - share/zsh/site-functions/_dex
      strict: true

about:
  homepage: https://github.com/dexidp/dex
  summary: OpenID Connect (OIDC) identity and OAuth 2.0 provider with pluggable connectors
  description: |
    Dex is an identity service that uses OpenID Connect to drive authentication for other apps.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://dexidp.io
  repository: https://github.com/dexidp/dex

extra:
  recipe-maintainers:
    - xhochy
